k-ingstagram/accounts/urls.py
from django.urls import path, re_path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('change-password/', views.password_change, name='password_change'),
    path('signup/', views.signup, name='signup'),
    path('edit/', views.edit_profile, name='edit_profile'),
    re_path(r'^(?P<username>[\w.@+-]+)/follow/$', views.user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollow/$', views.user_unfollow, name='user_unfollow'),
]

k-ingstagram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

from django_pydenticon.views import image as pydenticon_image


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('identicon/image/<path:data>/', pydenticon_image, name='pydenticon_image'),
    path('kingstagram/', include('kingstagram.urls')),
    path('', RedirectView.as_view(pattern_name="kingstagram:index"), name='root'),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

k-ingstagram/kingstagram/urls.py
from django.urls import path, re_path

from . import views

app_name = 'kingstagram'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/like/', views.post_like, name='post_like'),
    path('post/<int:pk>/unlike/', views.post_unlike, name='post_unlike'),
    path('post/<int:post_pk>/comment/new/', views.comment_new, name='comment_new'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page, name='user_page'),
]

k-ingstagram/kingstagram/models.py
import re

from django.db import models
from django.conf import settings
from django.urls import reverse


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(TimeStampedModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="my_post_set", on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="kingstagram/%Y/%m/%d")
    caption = models.CharField(max_length=500)
    tag_set = models.ManyToManyField('Tag', blank=True)
    location = models.CharField(max_length=100)
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_post_set", blank=True)

    def __str__(self):
        return self.caption

    def get_absolute_url(self):
        return reverse("kingstagram:post_detail", kwargs={"pk": self.pk})

    def extract_tag_list(self):
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.caption)
        tag_list = []
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        return tag_list

    def is_like_user(self, user):
        return self.like_user_set.filter(pk=user.pk).exists()

    class Meta:
        ordering = ['-id']


class Comment(TimeStampedModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

    class Meta:
        ordering = ['-id']


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

k-ingstagram/kingstagram/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['photo', 'caption', 'location', ]
        widgets = {
            'caption': forms.Textarea,
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message', ]
        labels = {
            "message": "",
        }
        widgets = {
            "message": forms.Textarea(attrs={"rows": 3, "placeholder": "댓글을 입력하세요."}),
        }

k-ingstagram/kingstagram/views.py
from datetime import timedelta
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import get_user_model
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from .forms import PostForm, CommentForm
from .models import Post


@login_required
def index(request):
    timesince = timezone.now() - timedelta(days=3)
    comment_form = CommentForm
    post_list = Post.objects.all()\
        .filter(
            Q(author=request.user) |
            Q(author__in=request.user.following_set.all())
        )\
        .filter(
            created_at__gte=timesince
        )

    suggested_user_list = get_user_model().objects.all()\
        .exclude(pk=request.user.pk)\
        .exclude(pk__in=request.user.following_set.all())[:3]

    return render(request, "kingstagram/index.html", {
        "post_list": post_list,
        "suggested_user_list": suggested_user_list,
        "comment_form": comment_form,
    })


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_set.add(*post.extract_tag_list())
            messages.success(request, "포스팅을 저장했습니다.")
            return redirect("/")  # FIXME: get_absolute_url 활용
    else:
        form = PostForm()

    return render(request, 'kingstagram/post_form.html', {
        "form": form
    })


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()
    return render(request, "kingstagram/post_detail.html", {
        'post': post,
        'comment_form': comment_form,
    })


@login_required
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.add(request.user)
    messages.success(request, f"{post.pk}번 포스팅을 좋아합니다.")
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)


@login_required
def post_unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.remove(request.user)
    messages.success(request, f"{post.pk}번 포스팅의 좋아요를 취소합니다.")
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)


@login_required
def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            if request.is_ajax():
                return render(request, "kingstagram/_comment.html", {
                    "comment": comment,
                })
            return redirect(comment.post)
    else:
        form = CommentForm()

    return render(request, "kingstagram/comment_form.html", {
        "form": form,
    })


def user_page(request, username):
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)
    post_list = Post.objects.filter(author=page_user)
    post_list_count = post_list.count()

    if request.user.is_authenticated:
        is_follow = request.user.following_set.filter(pk=page_user.pk).exists()
    else:
        is_follow = False

    return render(request, "kingstagram/user_page.html", {
        'page_user': page_user,
        'post_list': post_list,
        'post_list_count': post_list_count,
        'is_follow': is_follow,
    })

k-ingstagram/kingstagram/templates/kingstagram/_comment.html
{% load humanize %}

<div class="comment">
    <strong>{{ comment.author }}</strong>
    {{ comment.message }}
    <small class="text-muted">{{ comment.created_at|naturaltime }}</small>
</div>

k-ingstagram/kingstagram/templates/kingstagram/_post_card.html
{% load humanize bootstrap4 kingstagram_tags %}

<div class="card">

    <div class="card-header">
        <img src="{{ post.author.avatar_url }}" alt="" style="width: 32px; height: 32px;" class="mr-2"/>
        <a href="{% url 'kingstagram:user_page' post.author.username %}">
            {{ post.author.name }}
        </a>
    </div>

    <div class="card-body">
        <div>
            <img src="{{ post.photo.url }}" alt="" style="width: 100%;"/>
        </div>
        <div>
            {% if post|is_like_user:user %}
                <a href="{% url 'kingstagram:post_unlike' post.pk %}" style="color: inherit;">
                    <i class="fa fa-heart"></i>
                </a>
            {% else %}
                <a href="{% url 'kingstagram:post_like' post.pk %}" style="color: inherit;">
                    <i class="fa fa-heart-o"></i>
                </a>
            {% endif %}
        </div>
        <div id="post-{{ post.pk }}-comment-list" class="comment-list mt-3 mt-3">
            {% for comment in post.comment_set.all %}
                {% include 'kingstagram/_comment.html' %}
            {% endfor %}
        </div>
        <div>
            {% for tag in post.tag_set.all %}
                <span class="badge badge-primary">
                #{{ tag.name }}
            </span>
            {% endfor %}
        </div>
        <div>
            <a href="{{ post.get_absolute_url }}" style="" class="text-muted">
                <small>{{ post.created_at|naturaltime }}</small>
            </a>
        </div>
    </div>

    <div class="card-footer">
        <form id="post-{{ post.pk }}-comment-from" action="{% url 'kingstagram:comment_new' post.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <input type="submit" value="댓글 작성" class="btn btn-primary btn-block">
        </form>

        <script>
            $(function () {
                var form_id = "post-{{ post.pk }}-comment-from";
                $("#" + form_id).submit(function (e) {
                    e.preventDefault();

                    var options = {
                        success: function (responseText, statusText, xhr, $form) {
                            console.group("ajaxSubmit response");
                            console.log(responseText);
                            console.log(statusText);
                            console.log(xhr);
                            console.log($form);
                            console.groupEnd();

                            $("#post-5-comment-list").prepend(responseText);
                        }
                    };
                    $(this).ajaxSubmit(options);
                });
                console.log("document.ready.");
            });
        </script>
    </div>

</div>

k-ingstagram/kingstagram/templates/kingstagram/comment_form.html
{% extends 'kingstagram/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-md-3">
                {% include "_form.html" with form_title="댓글쓰기" submit_label="댓글쓰기" %}
            </div>
        </div>
    </div>
{% endblock %}

k-ingstagram/kingstagram/templates/kingstagram/index.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="row mb-3">
            <div class="col-sm-12">
                Hello, world
                <hr/>
                <a href="{% url 'kingstagram:post_new' %}" class="btn btn-primary">
                    새 포스팅
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                {% for post in post_list %}
                    <div class="mb-3">
                        {% include "kingstagram/_post_card.html" %}
                    </div>
                {% empty %}
                    포스팅이 없습니다.
                {% endfor %}
            </div>
            <div class="col-sm-4">
                {% include 'kingstagram/timeline_sidebar.html' %}
            </div>
        </div>
    </div>
{% endblock %}

k-ingstagram/kingstagram/templates/kingstagram/layout.html
{% extends 'layout.html' %}

k-ingstagram/kingstagram/templates/kingstagram/post_detail.html
{% extends 'kingstagram/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% include "kingstagram/_post_card.html" %}
            </div>
        </div>
    </div>
{% endblock %}

k-ingstagram/kingstagram/templates/kingstagram/post_form.html
{% extends 'kingstagram/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-md-3">
                {% include "_form.html" with form_title="새 포스팅 쓰기" submit_label="새 포스팅 쓰기" %}
            </div>
        </div>
    </div>
{% endblock %}

k-ingstagram/kingstagram/templates/kingstagram/timeline_sidebar.html
<div class="d-flex p-2 mb-3">
    <div class="mr-3">
        <img src="{{ user.avatar_url }}" alt="" class="rounded-circle"
             style="width: 48px; height: 48px;">
    </div>
    <div>
        {{ user.username }}<br/>
        <small class="text-muted">{{ user.name }}</small>
    </div>
</div>

<div class="card mb-3">
    <div class="card-header text-muted">
        Stories
    </div>
    <div class="card-body text-muted">
        Stories from people you will show up here.
    </div>
</div>

<div class="card mb-3">
    <div class="card-header text-muted">
        Suggestions for you
    </div>
    <div class="card-body text-muted">
        {% for suggested_user in suggested_user_list %}
            {% include 'kingstagram/timeline_sidebar_user_follow.html'%}
        {% empty %}
            추천 친구가 없습니다.
        {% endfor %}
    </div>
</div>

k-ingstagram/kingstagram/templates/kingstagram/timeline_sidebar_user_follow.html
<div class="d-flex mb-2">
    <div class="mr-3">
        <img src="{{ suggested_user.avatar_url }}" alt="" style="width: 32px; height: 32px;" class="rounded-circle"/>
    </div>
    <div class="">
        <a href="{% url 'kingstagram:user_page' suggested_user.username %}">
            {{ suggested_user.username }}
        </a>
    </div>
    <div class="ml-auto">
        <a href="{% url 'accounts:user_follow' suggested_user.username%}">Follow</a>
    </div>
</div>

k-ingstagram/kingstagram/templates/kingstagram/user_page.html
{% extends "kingstagram/layout.html" %}
{% load thumbnail %}

{% block content %}
    <div class="container">
        <div class="row pt-5 pb-5">
            <div class="col-sm-3" style="text-align: center;">
                <img src="{{ page_user.avatar_url }}" alt="" class="rounded-circle" style="width: 160px;"/>
            </div>
            <div class="col-sm-9">
                {{ page_user.username }}
                <a href="{% url 'accounts:edit_profile' %}" class="btn btn-secondary btn-sm">프로필 수정</a>
                {% if is_follow %}
                    <a href="{% url 'accounts:user_unfollow' page_user.username %}">
                        Unfollow
                    </a>
                {% else %}
                    <a href="{% url 'accounts:user_follow' page_user.username %}">
                        Follow
                    </a>
                {% endif %}
                <hr/>
                {{ post_list_count }} posts, 0 follows, 0 following
                <hr/>
                {{ page_user.name }}
            </div>
            <div class="row mt-3">
                {% for post in post_list %}
                    <div class="col-sm-4 mb-4">
                        <img src="{% thumbnail post.photo 512x512 crop %}" alt="{{ post.caption }}" style="width: 100%;"/>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}